apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: homepage-service
  template:
    metadata:
      labels:
        app: homepage-service
    spec:
      containers:
        - name: homepage-service
          image: vishnu1001/web-homepage:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app: homepage-service
  ports:
    - port: 3000
      targetPort: 3000
