apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: vishnu1001/web-orders:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
    - port: 3002
      targetPort: 3002
