name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cicd.yaml"
      - "src/nginx/**"
      - "src/homepage/**"
      - "src/orders/**"
      - "src/payment/**"
      - "helm/nginx-service-chart/**"
      - "helm/homepage-service-chart/**"
      - "helm/orders-service-chart/**"
      - "helm/payment-service-chart/**"

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest ./src/nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest ./src/homepage
          docker push ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-orders:latest ./src/orders
          docker push ${{ secrets.DOCKER_USERNAME }}/web-orders:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-payment:latest ./src/payment
          docker push ${{ secrets.DOCKER_USERNAME }}/web-payment:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Deployments with Helm
        run: |
          helm upgrade --install nginx-service ./helm/nginx-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-nginx \
            --set image.tag=latest \
            --atomic

          helm upgrade --install homepage-service ./helm/homepage-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-homepage \
            --set image.tag=latest \
            --atomic

          helm upgrade --install orders-service ./helm/orders-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-orders \
            --set image.tag=latest \
            --atomic

          helm upgrade --install payment-service ./helm/payment-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-payment \
            --set image.tag=latest \
            --atomic

      - name: Verify Deployments
        run: |
          helm list
          kubectl get all
