name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest

      - name: Build and Push Homepage Image
        uses: docker/build-push-action@v4
        with:
          context: ./homepage
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest

      - name: Build and Push Orders Image
        uses: docker/build-push-action@v4
        with:
          context: ./orders
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-orders:latest

      - name: Build and Push Payment Image
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-payment:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy Services
        run: |
          # Apply configurations
          kubectl apply -f nginx-service.yaml --validate=false
          kubectl apply -f homepage-service.yaml --validate=false
          kubectl apply -f orders-service.yaml --validate=false
          kubectl apply -f payment-service.yaml --validate=false

          # Force rollout restart to pull latest images
          kubectl rollout restart deployment/nginx
          kubectl rollout restart deployment/homepage-service
          kubectl rollout restart deployment/orders-service
          kubectl rollout restart deployment/payment-service

      - name: Wait for deployments
        run: |
          kubectl rollout status deployment/nginx
          kubectl rollout status deployment/homepage-service
          kubectl rollout status deployment/orders-service
          kubectl rollout status deployment/payment-service

      - name: Get Service URL
        run: minikube service nginx
