name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        service: ["nginx", "homepage", "orders", "payment"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web-${{ matrix.service }}:latest
          cache-to: type=inline

  deploy-services:
    needs: build-images
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy Services
        run: |
          kubectl delete all --all

          sleep 10

          kubectl apply -f nginx-service.yaml --validate=false
          kubectl apply -f homepage-service.yaml --validate=false
          kubectl apply -f orders-service.yaml --validate=false
          kubectl apply -f payment-service.yaml --validate=false

      - name: Wait for deployments
        run: |
          kubectl rollout status deployment/nginx
          kubectl rollout status deployment/homepage-service
          kubectl rollout status deployment/orders-service
          kubectl rollout status deployment/payment-service

      - name: Get Service URL
        run: minikube service nginx
