name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "nginx/**"
      - "homepage/**"
      - "orders/**"
      - "payment/**"
      - "nginx-service-chart/**"
      - "homepage-service-chart/**"
      - "orders-service-chart/**"
      - "payment-service-chart/**"

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          # Build and push all images in parallel
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest ./homepage
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-orders:latest ./orders
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-payment:latest ./payment

          docker push ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/web-orders:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/web-payment:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Update Deployments with Helm
        run: |
          # Update nginx service
          helm upgrade --install nginx-service ./nginx-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-nginx \
            --set image.tag=latest \
            --atomic

          # Update homepage service
          helm upgrade --install homepage-service ./homepage-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-homepage \
            --set image.tag=latest \
            --atomic

          # Update orders service
          helm upgrade --install orders-service ./orders-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-orders \
            --set image.tag=latest \
            --atomic

          # Update payment service
          helm upgrade --install payment-service ./payment-service-chart \
            --set image.name=${{ secrets.DOCKER_USERNAME }}/web-payment \
            --set image.tag=latest \
            --atomic

      - name: Verify Deployments
        run: |
          helm list
          kubectl get pods
