name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cicd.yaml"
      - "nginx/**"
      - "homepage/**"
      - "orders/**"
      - "payment/**"
      - "nginx-service.yaml"
      - "homepage-service.yaml"
      - "orders-service.yaml"
      - "payment-service.yaml"

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Nginx Image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-nginx:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web-nginx:latest
          cache-to: type=inline

      - name: Build & Push Homepage Image
        uses: docker/build-push-action@v4
        with:
          context: ./homepage
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-homepage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web-homepage:latest
          cache-to: type=inline

      - name: Build & Push Orders Image
        uses: docker/build-push-action@v4
        with:
          context: ./orders
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-orders:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web-orders:latest
          cache-to: type=inline

      - name: Build & Push Payment Image
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-payment:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web-payment:latest
          cache-to: type=inline

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy Services
        run: |
          # Apply configurations if they don't exist
          kubectl apply -f nginx-service.yaml --validate=false
          kubectl apply -f homepage-service.yaml --validate=false
          kubectl apply -f orders-service.yaml --validate=false
          kubectl apply -f payment-service.yaml --validate=false

          # Force rollout restart to pull latest images
          kubectl rollout restart deployment/nginx
          kubectl rollout restart deployment/homepage-service
          kubectl rollout restart deployment/orders-service
          kubectl rollout restart deployment/payment-service

      - name: Wait for deployments
        run: |
          kubectl rollout status deployment/nginx
          kubectl rollout status deployment/homepage-service
          kubectl rollout status deployment/orders-service
          kubectl rollout status deployment/payment-service
