name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Homepage Image
        uses: docker/build-push-action@v4
        with:
          context: ./homepage
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homepage:latest

      - name: Build and Push Orders Image
        uses: docker/build-push-action@v4
        with:
          context: ./orders
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/orders:latest

      - name: Build and Push Payment Image
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/payment:latest

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Update Minikube context
        run: minikube update-context

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Force rollout restart
        run: |
          kubectl rollout restart deployment/homepage-service
          kubectl rollout restart deployment/orders-service
          kubectl rollout restart deployment/payment-service
          kubectl rollout restart deployment/nginx

      - name: Verify deployments
        run: |
          kubectl get deployments
          kubectl get pods
